#!/usr/bin/env bash
# ssh config file

# Host *
# SendEnv LANG LC_*
# HashKnownHosts yes
# GSSAPIAuthentication yes
# GSSAPIDelegateCredentials no
# IdentityFile ~/.ssh/school
# PasswordAuthentication no


Host 54.236.25.118
IdentityFile ~/.ssh/school
PasswordAuthentication no
PubKeyAuthentication yes
